name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    if: ${{ github.repository == 'benthosdev/benthos' }}
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
        check-latest: true

    - name: Check Out Repo
      uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Release Notes
      run: ./resources/scripts/release_notes.sh > ./release_notes.md

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --release-notes=./release_notes.md --timeout 60m
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
        check-latest: true

    - name: Check Out Repo
      uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build
      run: make deps

    - name: Install Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    # Authenticates against google cloud using OIDC connector
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/1035679941503/locations/global/workloadIdentityPools/github-actions-ci/providers/github-actions'
        service_account: 'github-actions-benthos@artifacts-321215.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: 408.0.0

    - name: auth to gcr 
      run: gcloud auth configure-docker us-docker.pkg.dev -q

    - name: docker meta data
      id: docker_meta_data
      uses: docker/metadata-action@v4
      with:
        images: sodahealth/benthos
        tags: |
          type=raw,value=${{ github.ref_name }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./resources/docker/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: ${{ steps.docker_meta.outputs.tags }}
